# Generated by Django 3.2.4 on 2021-06-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cheeses.cheese'),
        ),
    ]
