# Generated by Django 3.2.4 on 2021-06-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cheeses.review'),
        ),
    ]
